# Generated by Django 4.1.2 on 2022-10-27 00:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=50)),
                ('dept', models.CharField(max_length=50)),
                ('serial_num', models.CharField(max_length=50)),
                ('inv_num', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='Date created')),
                ('assignedTo', models.CharField(max_length=100)),
                ('ID_inv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DBztop.inventory')),
            ],
        ),
        migrations.CreateModel(
            name='UserRegular',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('dept', models.CharField(max_length=50)),
                ('position', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='UserTech',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('dept', models.CharField(max_length=50)),
                ('position', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('roles', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned', models.BooleanField()),
                ('dateCreation', models.DateTimeField(verbose_name='Date created')),
                ('dateAssign', models.DateTimeField(verbose_name='Date assigned')),
                ('dateFinish', models.DateTimeField(verbose_name='Date finished')),
                ('ID_req', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DBztop.request')),
                ('ID_tech', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DBztop.usertech')),
            ],
        ),
        migrations.AddField(
            model_name='request',
            name='ID_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DBztop.userregular'),
        ),
        migrations.CreateModel(
            name='ItemType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typeOf', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=100)),
                ('brand', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=50)),
                ('ID_inv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DBztop.inventory')),
            ],
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='Date logged')),
                ('updated', models.BooleanField()),
                ('user', models.CharField(max_length=100)),
                ('ID_inv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DBztop.inventory')),
            ],
        ),
        migrations.CreateModel(
            name='Consumables',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typeOf', models.CharField(max_length=50)),
                ('brand', models.CharField(max_length=50)),
                ('ID_inv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DBztop.inventory')),
            ],
        ),
    ]
