# Generated by Django 4.1.2 on 2022-10-27 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DBztop', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='userregular',
            constraint=models.UniqueConstraint(fields=('name', 'email'), name='unique_employee'),
        ),
        migrations.AddConstraint(
            model_name='usertech',
            constraint=models.UniqueConstraint(fields=('name', 'email'), name='unique_technician'),
        ),
    ]
