# Generated by Django 4.1.2 on 2022-12-01 22:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DBztop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='dept',
            field=models.CharField(choices=[('centro_graduados', 'Centro de Graduados e Investigación en Química'), ('ciencias_basicas', 'Ciencias Básicas'), ('desarrollo_academico', 'Desarrollo Académico'), ('division_estudios_prof', 'División de Estudios Profesionales'), ('division_estudios_posgrado', 'División de Estudios de Posgrado e Investigación'), ('economico_administrativas', 'Económico Administrativas'), ('electrica_electronica', 'Eléctrica y Electrónica'), ('ing_industrial', 'Ingeniería Industrial'), ('metal_mecanica', 'Metal Mecánica'), ('sistemas', 'Sistemas y Computación'), ('dept_ingenieria', 'Departamento de Ingeniería'), ('quimica_bioquimica', 'Química y Bioquímica'), ('centro_info', 'Centro de Información'), ('comunicacion_difusion', 'Comunicación y Difusión'), ('act_extraescolares', 'Actividades Extraescolares'), ('vinculacion', 'Gestión Tecnológica y Vinculación'), ('planeacion', 'Planeación, Programación y Presupuestación'), ('servicios_escolares', 'Servicios Escolares'), ('centro_computo', 'Centro de Cómputo'), ('recursos_financieros', 'Recursos Financieros'), ('mantenimiento', 'Mantenimiento y Equipo'), ('recursos_humanos', 'Recursos Humanos'), ('materiales_servicios', 'Materiales y Servicios'), ('sistema_gestion_calidad', 'Sistema de Gestión de Calidad'), ('transportes', 'Transportes IT Tijuana'), ('ciia', 'CIIA')], max_length=50),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='location',
            field=models.CharField(choices=[('tomas aquino', 'Tomás Aquino'), ('otay', 'Otay'), ('fracc monterrey', 'Fracc. Monterrey')], max_length=50),
        ),
        migrations.AlterField(
            model_name='request',
            name='assignedTo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='DBztop.usertech'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='ID_tech',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='DBztop.usertech'),
        ),
        migrations.AlterField(
            model_name='userregular',
            name='dept',
            field=models.CharField(choices=[('centro_graduados', 'Centro de Graduados e Investigación en Química'), ('ciencias_basicas', 'Ciencias Básicas'), ('desarrollo_academico', 'Desarrollo Académico'), ('division_estudios_prof', 'División de Estudios Profesionales'), ('division_estudios_posgrado', 'División de Estudios de Posgrado e Investigación'), ('economico_administrativas', 'Económico Administrativas'), ('electrica_electronica', 'Eléctrica y Electrónica'), ('ing_industrial', 'Ingeniería Industrial'), ('metal_mecanica', 'Metal Mecánica'), ('sistemas', 'Sistemas y Computación'), ('dept_ingenieria', 'Departamento de Ingeniería'), ('quimica_bioquimica', 'Química y Bioquímica'), ('centro_info', 'Centro de Información'), ('comunicacion_difusion', 'Comunicación y Difusión'), ('act_extraescolares', 'Actividades Extraescolares'), ('vinculacion', 'Gestión Tecnológica y Vinculación'), ('planeacion', 'Planeación, Programación y Presupuestación'), ('servicios_escolares', 'Servicios Escolares'), ('centro_computo', 'Centro de Cómputo'), ('recursos_financieros', 'Recursos Financieros'), ('mantenimiento', 'Mantenimiento y Equipo'), ('recursos_humanos', 'Recursos Humanos'), ('materiales_servicios', 'Materiales y Servicios'), ('sistema_gestion_calidad', 'Sistema de Gestión de Calidad'), ('transportes', 'Transportes IT Tijuana'), ('ciia', 'CIIA')], max_length=50),
        ),
        migrations.AlterField(
            model_name='usertech',
            name='dept',
            field=models.CharField(choices=[('centro_graduados', 'Centro de Graduados e Investigación en Química'), ('ciencias_basicas', 'Ciencias Básicas'), ('desarrollo_academico', 'Desarrollo Académico'), ('division_estudios_prof', 'División de Estudios Profesionales'), ('division_estudios_posgrado', 'División de Estudios de Posgrado e Investigación'), ('economico_administrativas', 'Económico Administrativas'), ('electrica_electronica', 'Eléctrica y Electrónica'), ('ing_industrial', 'Ingeniería Industrial'), ('metal_mecanica', 'Metal Mecánica'), ('sistemas', 'Sistemas y Computación'), ('dept_ingenieria', 'Departamento de Ingeniería'), ('quimica_bioquimica', 'Química y Bioquímica'), ('centro_info', 'Centro de Información'), ('comunicacion_difusion', 'Comunicación y Difusión'), ('act_extraescolares', 'Actividades Extraescolares'), ('vinculacion', 'Gestión Tecnológica y Vinculación'), ('planeacion', 'Planeación, Programación y Presupuestación'), ('servicios_escolares', 'Servicios Escolares'), ('centro_computo', 'Centro de Cómputo'), ('recursos_financieros', 'Recursos Financieros'), ('mantenimiento', 'Mantenimiento y Equipo'), ('recursos_humanos', 'Recursos Humanos'), ('materiales_servicios', 'Materiales y Servicios'), ('sistema_gestion_calidad', 'Sistema de Gestión de Calidad'), ('transportes', 'Transportes IT Tijuana'), ('ciia', 'CIIA')], max_length=50),
        ),
    ]
