# Generated by Django 4.1.2 on 2022-10-27 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DBztop', '0002_userregular_unique_employee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='dateAssign',
            field=models.DateTimeField(null=True, verbose_name='Date assigned'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='dateFinish',
            field=models.DateTimeField(null=True, verbose_name='Date finished'),
        ),
    ]
