# Generated by Django 4.1.2 on 2022-10-27 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DBztop', '0003_alter_ticket_dateassign_alter_ticket_datefinish'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='dateAssign',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date assigned'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='dateFinish',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date finished'),
        ),
    ]
