# Generated by Django 4.1.2 on 2022-10-28 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DBztop', '0004_alter_ticket_dateassign_alter_ticket_datefinish'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='inventory',
            constraint=models.UniqueConstraint(fields=('serial_num',), name='unique_serial'),
        ),
        migrations.AddConstraint(
            model_name='inventory',
            constraint=models.UniqueConstraint(fields=('inv_num',), name='unique_inv'),
        ),
    ]
