# Generated by Django 4.1.2 on 2022-11-01 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DBztop', '0005_inventory_unique_serial_inventory_unique_inv'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='inventory',
            constraint=models.CheckConstraint(check=models.Q(('inv_num__endswith', '_ITT'), ('inv_num__endswith', '_Otay'), ('inv_num__endswith', '_Radio'), _connector='OR'), name='check_inv_location'),
        ),
    ]
