# Generated by Django 4.1.2 on 2022-11-01 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DBztop', '0006_inventory_check_inv_location'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='inventory',
            constraint=models.CheckConstraint(check=models.Q(('location__iexact', 'tomas aquino'), ('location__iexact', 'otay'), ('location__iexact', 'fracc monterrey'), _connector='OR'), name='check_location'),
        ),
    ]
